#!/usr/bin/env python3
"""Load TorchScript ResNet-18 model and run inference for verification."""

import os

import numpy as np
import torch
import torchvision


if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser(
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    parser.add_argument(
        "batch_size",
        help="Number of images in the batch",
        type=int,
    )
    parser.add_argument(
        "--model_file",
        help="Path to TorchScript model file",
        type=str,
        default="torchscript_resnet18_model_cpu.pt",
    )
    parser.add_argument(
        "--data_dir",
        help="Path to the data directory",
        type=str,
        default=os.path.join(os.path.dirname(__file__), "data"),
    )
    parser.add_argument(
        "--precision",
        help="Working precision",
        type=str,
        default="float32",
    )
    parsed_args = parser.parse_args()
    batch_size = parsed_args.batch_size
    model_file = parsed_args.model_file
    data_dir = parsed_args.data_dir
    precision = getattr(np, parsed_args.precision)

    # Read transposed binary data generated by generate_input_batch.py
    transposed_shape = [224, 224, 3, batch_size]
    tensor_file = os.path.join(data_dir, f"image_batch_{batch_size}.dat")
    np_data = np.fromfile(tensor_file, dtype=precision)
    np_data = np_data.reshape(transposed_shape)
    np_data = np_data.transpose()
    input_tensor = torch.from_numpy(np_data)

    # Load TorchScript model and run inference
    model = torch.jit.load(model_file)
    with torch.inference_mode():
        output = model.forward(input_tensor)

    # Print top result per batch element
    probabilities = torch.nn.functional.softmax(output, dim=1)
    top_prob, top_idx = torch.topk(probabilities, 1, dim=1)
    for i in range(batch_size):
        print(f"{i}: class {top_idx[i].item()}, probability = {top_prob[i].item():.6f}")
    print("Python verification passed.")
