# Time for the practical

## Exercise 0 -- Hello Fortran and PyTorch!

:::{.fragment}
**Question:** What are people's experience levels with and use cases of Fortran and PyTorch?
:::
\

:::{.fragment}
Navigate to `exercises/exercise_00/` where you will see both Python and
Fortran files.
:::

## Python

`hello_pytorch.py` defines a net `SimpleNet` that takes an input vector of length 5
and multiplies it by 2.

Note:

  - the `nn.Module` class
  - the `forward()` method

Running:
```default
python hello_pytorch.py
```

should produce the output:
```default
Input is  tensor([0., 1., 2., 3., 4.]).
Output is tensor([0., 2., 4., 6., 8.]).
```


## Compilers and CMake

First we will check that we have a Fortran compiler and CMake installed:

Running:
```default
gfortran --version
cmake --version
```

\

::::{.columns}
:::{.column width=60%}
Should produce output similar to:
```default
GNU Fortran (Homebrew GCC 14.1.0_1) 14.1.0
Copyright (C) 2024 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or
FITNESS FOR A PARTICULAR PURPOSE.

cmake version 3.31.0
CMake suite maintained and supported by Kitware (kitware.com/cmake).
```
:::
:::{.column width=40%}
and not:
```default
bash: command not found: gfortran
bash: command not found: cmake
```
:::
::::

:::{.aside}
Check that CMake version >= 3.18 and gcc >= 9 as required for FTorch.
:::

## Fortran

The file `hello_fortran.f90` contains a program to take an input array and call a
subroutine to multiply it by two before printing the result.

The subroutine is contained in a separate module `math_mod.f90`, however.


## Fortran

Now we will compile the code using CMake.

:::{.fragment}
First create a build directory and generate build scripts using CMake:
```default
mkdir build
cd build
cmake ..
```
:::

:::{.fragment}
We then use CMake again to build the executable:
```default
cmake --build .
```
:::

:::{.fragment}
Run the compiled executable:
```default
./hello_fortran
```
should produce the output
```default
 Hello, World!
 Input:     0.00000000        1.00000000        2.00000000        3.00000000        4.00000000
 Output:    0.00000000        2.00000000        4.00000000        6.00000000        8.00000000
```
:::

:::{.aside}
CMake handles the compilation and linking of both Fortran files.
:::
